# -*- coding: utf-8 -*-
"""IBM_Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o04Ua_4F-UsuouOquwmppLVUxSQhi03q

## Basic Python

1. Split this *string*`
"""

c = "Hi there Sam !"
print("List of words after splitting:",c.split(" "))

"""2. Use .format() to print the following string.

Output should be: The diameter of Earth is 12742 kilometers.
"""

Planet = "Earth"
Diameter = 12742
print("The diameter of {} is {} kilometers.".format(Planet,Diameter))

"""3. In this nest dictionary grab the word hello"""

d = {"k1":[1,2,3,{"tricky":["oh", "man", "inception",{"target":[1,2,3,"hello"]}]}]}
print(d["k1"][3]["tricky"][3]["target"][3])

"""## Numpy

4.1 Create an array of 10 zeros
"""

import numpy as np

arr1 = np.zeros(10)
print("Array of 10 zeros:",arr1)

"""4.2 Create an array of 10 fives"""

arr2 = 5*np.ones(10)
print("Array of 10 fives:",arr2)

"""5. Create an array of all the even integers from 20 to 35"""

a = 20
b = 35
arr3 = []
for i in range(a,b+1):
  if (i%2==0):
    arr3.append(i)
print("The required array:",arr3)

"""6. Create a 3x3 matrix with values ranging from 0 to 8"""

n = 8
mat = np.arange(0,n+1)
mat = mat.reshape(3,3)
print("Matrix:\n",mat)

"""7. Concatenate a and b

   a = np.array([1,2,3]), b = np.array([4,5,6])
"""

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print("Concatenated Array:\n",c)

"""## Pandas

8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

import random
l1=[]
for i in range(6):
  a = random.randint(0,6)
  l1.append(a)
l1 = np.array(l1)
data = l1.reshape(3,2)
df1 = pd.DataFrame(data,columns=["A","B"],index=["C","D","E"])
df1

"""9. Generate the series of dates from 1st Jan,2023 to 10th Feb,2023"""

pd.date_range(start="1-1-2023", end="10-02-2023", freq="2D")

"""10. Create 2D list to DataFrame"""

l2 = [[1,2,3],[4,5,6],[7,8,9]]
df2 = pd.DataFrame(l2)
df2

